/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.8-dev */

#ifndef PB_TEST_PB_H_INCLUDED
#define PB_TEST_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _SimpleTest {
    int32_t test_value;
} SimpleTest;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define SimpleTest_init_default                  {0}
#define SimpleTest_init_zero                     {0}

/* Field tags (for use in manual encoding/decoding) */
#define SimpleTest_test_value_tag                1

/* Struct field encoding specification for nanopb */
#define SimpleTest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    test_value,        1)
#define SimpleTest_CALLBACK NULL
#define SimpleTest_DEFAULT NULL

extern const pb_msgdesc_t SimpleTest_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define SimpleTest_fields &SimpleTest_msg

/* Maximum encoded size of messages (where known) */
#define SimpleTest_size                          11

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
